#!/usr/bin/env node

process.stdout.write(`${process.env.OWNED_PROCESS_TEST_PGID} ${process.env.OWNED_PROCESS_TEST_PGID} S\n`)
process.stdout.write(`99999 ${process.env.OWNED_PROCESS_TEST_PGID} Z\n`)
